---
all:
  hosts:
  children:
    master:
      hosts:
        kubemaster:
          ansible_host: 192.168.0.241

    worker:
      hosts:
        kubenode01:
          ansible_host: 192.168.0.243
        kubenode02:
          ansible_host: 192.168.0.244

    mgmt:
      hosts:
        kubemgmt1:
          ansible_host: 192.168.0.240

